"""Add verify columns in User Model

Revision ID: 6dcc4b1b6b75
Revises: 12dcd7ed04bb
Create Date: 2024-10-09 15:20:56.940281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dcc4b1b6b75'
down_revision = '12dcd7ed04bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email_verification_code')

    # ### end Alembic commands ###
